FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src

COPY Server/*.csproj ./Server/
COPY Common/*.csproj ./Common/
RUN dotnet restore ./Server/Server.csproj

COPY Server/. ./Server/
COPY Common/. ./Common/
RUN dotnet publish ./Server/Server.csproj -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/runtime:10.0 AS final

WORKDIR /app
COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "Server.dll"]