FROM mcr.microsoft.com/dotnet/sdk:10.0

WORKDIR /app

COPY Client ./Client
COPY Common ./Common

RUN dotnet publish ./Client/Client.csproj -c Release -o /app/out

ENTRYPOINT ["dotnet", "/app/out/Client.dll"]