FROM mcr.microsoft.com/dotnet/sdk:10.0

WORKDIR /app

COPY Server ./Server
COPY Common ./Common

RUN dotnet publish ./Server/Server.csproj -c Release -o /app/out

ENTRYPOINT ["dotnet", "/app/out/Server.dll"]