FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY Common/Common.csproj Common/
COPY Client/Client.csproj Client/
RUN dotnet restore Client/Client.csproj

COPY Common/. Common/
COPY Client/. Client/
RUN dotnet publish Client/Client.csproj -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/runtime:10.0 AS final
WORKDIR /app
COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "Client.dll"]
